
package moduloTransferencia.infraestructura.servicios.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Medio_de_PagoService", targetNamespace = "http://servicios.infraestructura.moduloCompra/", wsdlLocation = "file:/home/manuel/Documentos/Clases/Tecnologo/Java%20EE/Java-EE-Laboratorio/jakartaee-laboratorio-pasarela/src/main/webapp/WEB-INF/wsdl/MedioDePagoService.wsdl")
public class MedioDePagoService
    extends Service
{

    private final static URL MEDIODEPAGOSERVICE_WSDL_LOCATION;
    private final static WebServiceException MEDIODEPAGOSERVICE_EXCEPTION;
    private final static QName MEDIODEPAGOSERVICE_QNAME = new QName("http://servicios.infraestructura.moduloCompra/", "Medio_de_PagoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/manuel/Documentos/Clases/Tecnologo/Java%20EE/Java-EE-Laboratorio/jakartaee-laboratorio-pasarela/src/main/webapp/WEB-INF/wsdl/MedioDePagoService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MEDIODEPAGOSERVICE_WSDL_LOCATION = url;
        MEDIODEPAGOSERVICE_EXCEPTION = e;
    }

    public MedioDePagoService() {
        super(__getWsdlLocation(), MEDIODEPAGOSERVICE_QNAME);
    }

    public MedioDePagoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEDIODEPAGOSERVICE_QNAME, features);
    }

    public MedioDePagoService(URL wsdlLocation) {
        super(wsdlLocation, MEDIODEPAGOSERVICE_QNAME);
    }

    public MedioDePagoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEDIODEPAGOSERVICE_QNAME, features);
    }

    public MedioDePagoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MedioDePagoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MedioDePago
     */
    @WebEndpoint(name = "Medio_de_PagoPort")
    public MedioDePago getMedioDePagoPort() {
        return super.getPort(new QName("http://servicios.infraestructura.moduloCompra/", "Medio_de_PagoPort"), MedioDePago.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MedioDePago
     */
    @WebEndpoint(name = "Medio_de_PagoPort")
    public MedioDePago getMedioDePagoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicios.infraestructura.moduloCompra/", "Medio_de_PagoPort"), MedioDePago.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEDIODEPAGOSERVICE_EXCEPTION!= null) {
            throw MEDIODEPAGOSERVICE_EXCEPTION;
        }
        return MEDIODEPAGOSERVICE_WSDL_LOCATION;
    }

}
