
package moduloTransferencia.infraestructura.servicios.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Medio_de_Pago", targetNamespace = "http://servicios.infraestructura.moduloCompra/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MedioDePago {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Realizar_Compra")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Realizar_Compra", targetNamespace = "http://servicios.infraestructura.moduloCompra/", className = "moduloTransferencia.infraestructura.servicios.impl.RealizarCompra")
    @ResponseWrapper(localName = "Realizar_CompraResponse", targetNamespace = "http://servicios.infraestructura.moduloCompra/", className = "moduloTransferencia.infraestructura.servicios.impl.RealizarCompraResponse")
    @Action(input = "http://servicios.infraestructura.moduloCompra/Medio_de_Pago/Realizar_CompraRequest", output = "http://servicios.infraestructura.moduloCompra/Medio_de_Pago/Realizar_CompraResponse")
    public int realizarCompra(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
