
package moduloCompra.infraestructura.servicios.Medio_De_Pago;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BancoAPIimplService", targetNamespace = "http://impl.servicios.infraestructura.moduloTransferencia/", wsdlLocation = "file:/home/manuel/Documentos/Clases/Tecnologo/Java%20EE/Java-EE-Laboratorio/jakartaee-laboratorio-pasarela/src/main/webapp/WEB-INF/wsdl/BancoAPIimplService.wsdl")
public class BancoAPIimplService
    extends Service
{

    private final static URL BANCOAPIIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BANCOAPIIMPLSERVICE_EXCEPTION;
    private final static QName BANCOAPIIMPLSERVICE_QNAME = new QName("http://impl.servicios.infraestructura.moduloTransferencia/", "BancoAPIimplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/manuel/Documentos/Clases/Tecnologo/Java%20EE/Java-EE-Laboratorio/jakartaee-laboratorio-pasarela/src/main/webapp/WEB-INF/wsdl/BancoAPIimplService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANCOAPIIMPLSERVICE_WSDL_LOCATION = url;
        BANCOAPIIMPLSERVICE_EXCEPTION = e;
    }

    public BancoAPIimplService() {
        super(__getWsdlLocation(), BANCOAPIIMPLSERVICE_QNAME);
    }

    public BancoAPIimplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANCOAPIIMPLSERVICE_QNAME, features);
    }

    public BancoAPIimplService(URL wsdlLocation) {
        super(wsdlLocation, BANCOAPIIMPLSERVICE_QNAME);
    }

    public BancoAPIimplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANCOAPIIMPLSERVICE_QNAME, features);
    }

    public BancoAPIimplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BancoAPIimplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BancoAPIimpl
     */
    @WebEndpoint(name = "BancoAPIimplPort")
    public BancoAPIimpl getBancoAPIimplPort() {
        return super.getPort(new QName("http://impl.servicios.infraestructura.moduloTransferencia/", "BancoAPIimplPort"), BancoAPIimpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BancoAPIimpl
     */
    @WebEndpoint(name = "BancoAPIimplPort")
    public BancoAPIimpl getBancoAPIimplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.servicios.infraestructura.moduloTransferencia/", "BancoAPIimplPort"), BancoAPIimpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANCOAPIIMPLSERVICE_EXCEPTION!= null) {
            throw BANCOAPIIMPLSERVICE_EXCEPTION;
        }
        return BANCOAPIIMPLSERVICE_WSDL_LOCATION;
    }

}
