
package moduloCompra.infraestructura.servicios.Medio_De_Pago;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BancoAPIimpl", targetNamespace = "http://impl.servicios.infraestructura.moduloTransferencia/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BancoAPIimpl {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Realizar_Transferencia")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Realizar_Transferencia", targetNamespace = "http://impl.servicios.infraestructura.moduloTransferencia/", className = "moduloCompra.infraestructura.servicios.Medio_De_Pago.RealizarTransferencia")
    @ResponseWrapper(localName = "Realizar_TransferenciaResponse", targetNamespace = "http://impl.servicios.infraestructura.moduloTransferencia/", className = "moduloCompra.infraestructura.servicios.Medio_De_Pago.RealizarTransferenciaResponse")
    @Action(input = "http://impl.servicios.infraestructura.moduloTransferencia/BancoAPIimpl/Realizar_TransferenciaRequest", output = "http://impl.servicios.infraestructura.moduloTransferencia/BancoAPIimpl/Realizar_TransferenciaResponse")
    public int realizarTransferencia(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
